// <auto-generated />
namespace EatUP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addcolum_for_CSform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolum_for_CSform));
        
        string IMigrationMetadata.Id
        {
            get { return "202111260817058_addcolum_for_CSform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
