// <auto-generated />
namespace EatUP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imageBYTEtostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageBYTEtostring));
        
        string IMigrationMetadata.Id
        {
            get { return "202106091737358_imageBYTEtostring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
